dist: focal
language: node_js
matrix:
  fast_finish: true
node_js:
  - 16
branches:
  only:
    - master
    # tags
    - /^\d+\.\d+\.\d+(\-beta.\d+)?$/
env:
  global:
    - NODE_OPTIONS="--max-old-space-size=8192"
    # REGISTRY_TOKEN
    - secure: 'i1xWUxgKq3Uv1aUmSoAdlzn/UgBu6i2FVr28jgnAbqylrpMP+7ix65YTjnLEbyWKHr8Irngz1ydN/Y4ITk16BWKeaum7aBEPmemuVEFu83l0YrE1NRELoL1HAwvMcs4PuO/Rq1t+LOQcaci7Gcn3BZKnDIWizKHqMDI8XnomrtqpWzthVQptj+CLO2EutNON52Gm28naQfKdH4818ZEGwqiX7FuJI8Jz+zeVFtTn7hhpW84ZASeSmhWIjuhHmOQ9XU6a7C+x6Vf/kZu/Q/lDrGJlA0XFxcJOWHEit5vCTIf3WWW98eL+rdpdhVLFCifUEkuVN33QYNlEMDJ16/P3PoXuMEOxUCa8kyQ+aNumQiE47GCnZfZ6QeW8COx2fyD3T0dPeB/bCDQFfdVR0tqt+ZMKh0lfTM6daeqsOCGKBhA582MKUzY4rSa+/k+hXkHUAXY6714ZMikrfqfK4gzsYnfui5RdB+/9ekDX+wEN9CQeg19QbYIOWctZQ1/0HtHerQqt2ViSBJ+Na4MsW4bzaUPlYqrdjCBPQJrGUP4Jn2bQiO/nkfG5KbQu9lF27TS0hxgt/MXH2aiVa74zo5P1yypQUqzJV3wMyp2Top90IDaD6+7uYnShR0I0s0o3p6KZzNPLKNAG3kNrJs1ilZ1YaBNFYesOR5PyhIoi8tsMA8g='
    # GITHUB_TOKEN
    - secure: 'PrqAZmOaopscjbQbBXGxbZORI0Sk5wifhkWMFcMxOP3Nt8H5a0CuC1strA3SKkhLL11VnjgPRx79sQHOE66+6GQAngoILONsJ2uegBnhKStIdl2uenAgIb8Ehr8Ag4TTQiKSnUlpbSuJ5YxcSFipZxrY3X7RiOnY/P0raTErZH0dV/kW6UqKrx7ctlHTuxww3lHnLTh/ISHprsxaeRnEvYAT50ouVI5fkKaehMCkHUelu7rMHwCeLnUswtilODqhZo1MAOrnQjB45qNRm1H646vGofI+0k1LdtxdCedvoRTwwn4spX50Qc6ydxKajidj+BDTsJ+dPPEgx7QaHPXNZs/CF0iFDkxuYugGF5AtRSwDu+kujvOeH/J6WEwHSyzz8ROHoFnYyNjF82tn9DCL97nBvoAbaVu/Y7gmCC2sv9uyMZpey8Dy0XWYgCrXtiyg6gjgvTjG+JNLwRum1Oy7BWalle73ow2BMz/IlJGtq3tXMQ80xdmMYYdseITQr2ES6NSoC2xH9Ov5IszMVPjpxarXUc1C5eJWK6uEnbsfyZtOv3lSXQ8rForank8nGQowYxJ531FEbbgVMWsFtg5A5bwAeYmSt9MDrOg/Rkt6XxDfAxWIreo7Qu4aDQ9XN5ZhBBnqmrk0dxURyiLS295p2OvmHTeLsZL40p2E2/gwEwo='
    - MATTERMOST_CHANNEL='{"dev":"cozy-notes","beta":"cozy-notes,publication","stable":"cozy-notes,publication"}'
    # Mattermost URL travis encrypt ... -r cozy/cozy-notes
    - secure: "atWcibvx3jjadks9/8dh0VL08P0x03epeA3Z5csuvJp2mh9Hwww+Hfaa4uZ7ygj/6fku+hQzguNS1F8z48cxcUJZl8WjNhNywgiOW/Bdub1G+T9hPBJMOLT5X+OY+KEE8VlBicy+Ed6DTTlQekAXsHJRfMDwkY55yW9PISWVXonm8bROWduyyN7HH2xobsyC5eei2fFRsfKKC4VIqgANku1oDWwsssBDtlDBQ9B1aYGmrRZAVx0tUPIcjD2syY/0OB7XWPh+xz0t9AZkC4TK9JRSxXZAHxMsPyVRhXAu72iVyU/3qPUXMM0fRanerwxvpQbYy+vF2/Pr8euOBGZ6QEbUCKal/yeqTOLWbYxlXqEKXhuCAhwwGrA18FB8YLsS1H8QBWlqT6mUAFZIKkugDthsQSA0dnD4pOT4U1NjKZ81ZJKvORScVHrM1U5OSLtR0G3/KfR8hegh47qPZdJl3mKkMkvful+fzE5OnkxPaw/xxvLQecoYpMaAqgwXy2hMmRM++HLdt9aBQTHbVHtPeoLqoaVGzRnC/Cg601dsfQxDbSXvoU5qjDK2t7FD2Dgu44mALFdCd1gs+XLBR+RgxPeQxqbn8AoFr9OJ/eXa1tTK1yZ0YNo6yz6DM56MhZWMRpmVHeECF85Jlh6eGInJNxZALGxh/3hJ27kTpGHRDsE="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test --coverage
  - yarn build
  - yarn bundlemon
before_deploy:
  - yarn add cozy-app-publish
deploy:
  - provider: script
    repo: cozy/cozy-notes
    skip-cleanup: true
    # deploy the build on a build branch and publish to the Cozy registry
    script: DEPLOY_BRANCH=ci-build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  - provider: script
    repo: cozy/cozy-notes
    skip-cleanup: true
    # publish stable or beta versions using Github Releases (git tag)
    script: DEPLOY_BRANCH=ci-build && yarn deploy && yarn cozyPublish
    on:
      tags: true
