dist: focal
language: node_js
matrix:
  fast_finish: true
node_js:
  - 16
branches:
  only:
    - master
    # tags
    - /^\d+\.\d+\.\d+(\-beta.\d+)?$/
env:
  global:
    - NODE_OPTIONS="--max-old-space-size=8192"
    # REGISTRY_TOKEN
    - secure: 'i1xWUxgKq3Uv1aUmSoAdlzn/UgBu6i2FVr28jgnAbqylrpMP+7ix65YTjnLEbyWKHr8Irngz1ydN/Y4ITk16BWKeaum7aBEPmemuVEFu83l0YrE1NRELoL1HAwvMcs4PuO/Rq1t+LOQcaci7Gcn3BZKnDIWizKHqMDI8XnomrtqpWzthVQptj+CLO2EutNON52Gm28naQfKdH4818ZEGwqiX7FuJI8Jz+zeVFtTn7hhpW84ZASeSmhWIjuhHmOQ9XU6a7C+x6Vf/kZu/Q/lDrGJlA0XFxcJOWHEit5vCTIf3WWW98eL+rdpdhVLFCifUEkuVN33QYNlEMDJ16/P3PoXuMEOxUCa8kyQ+aNumQiE47GCnZfZ6QeW8COx2fyD3T0dPeB/bCDQFfdVR0tqt+ZMKh0lfTM6daeqsOCGKBhA582MKUzY4rSa+/k+hXkHUAXY6714ZMikrfqfK4gzsYnfui5RdB+/9ekDX+wEN9CQeg19QbYIOWctZQ1/0HtHerQqt2ViSBJ+Na4MsW4bzaUPlYqrdjCBPQJrGUP4Jn2bQiO/nkfG5KbQu9lF27TS0hxgt/MXH2aiVa74zo5P1yypQUqzJV3wMyp2Top90IDaD6+7uYnShR0I0s0o3p6KZzNPLKNAG3kNrJs1ilZ1YaBNFYesOR5PyhIoi8tsMA8g='
    # GITHUB_TOKEN
    - secure: 'PrqAZmOaopscjbQbBXGxbZORI0Sk5wifhkWMFcMxOP3Nt8H5a0CuC1strA3SKkhLL11VnjgPRx79sQHOE66+6GQAngoILONsJ2uegBnhKStIdl2uenAgIb8Ehr8Ag4TTQiKSnUlpbSuJ5YxcSFipZxrY3X7RiOnY/P0raTErZH0dV/kW6UqKrx7ctlHTuxww3lHnLTh/ISHprsxaeRnEvYAT50ouVI5fkKaehMCkHUelu7rMHwCeLnUswtilODqhZo1MAOrnQjB45qNRm1H646vGofI+0k1LdtxdCedvoRTwwn4spX50Qc6ydxKajidj+BDTsJ+dPPEgx7QaHPXNZs/CF0iFDkxuYugGF5AtRSwDu+kujvOeH/J6WEwHSyzz8ROHoFnYyNjF82tn9DCL97nBvoAbaVu/Y7gmCC2sv9uyMZpey8Dy0XWYgCrXtiyg6gjgvTjG+JNLwRum1Oy7BWalle73ow2BMz/IlJGtq3tXMQ80xdmMYYdseITQr2ES6NSoC2xH9Ov5IszMVPjpxarXUc1C5eJWK6uEnbsfyZtOv3lSXQ8rForank8nGQowYxJ531FEbbgVMWsFtg5A5bwAeYmSt9MDrOg/Rkt6XxDfAxWIreo7Qu4aDQ9XN5ZhBBnqmrk0dxURyiLS295p2OvmHTeLsZL40p2E2/gwEwo='
    - MATTERMOST_CHANNEL='{"dev":"cozy-notes","beta":"cozy-notes,publication","stable":"cozy-notes,publication"}'
    # MATTERMOST_HOOK_URL travis encrypt ... -r cozy/cozy-notes
    - secure: "VYOZDkL38W1Klrw9SwUtSa8axFLs32xf6r36zXlo82v4RA3qWVlzJdG+Lvpf6TcXwsuNKo5nbwSJaPYsIKmCc0nlYOxoPXKS1Mfa7B8VXrX1S5p/29RrWgEeM+9nrx52XTRDgW7LPqUpQIL1alA3u+OIUQISU64eysFTJFWofrp2q2Yx78nAAWBwhc6s0UFk0oBJdeeX7l16pLggkiuKyTupnCJp6dnnD3XUH4ewELfVKDnOwqLPvZLcjLpCqCGqQ/pO9/oRNeCQKK2mP4yhePJ+UDt4GkbPCCQCce/PJVWPlOabBHNdiiFeOcH2z5aX51T75i6I3vPUf41tAokZAPz9ilbo2edxeIPThbe+XaxbL1Fkh7BFIiY4kOAkj+oF+kXA6ui9Jfkq5oSA/SlB4nfUkTUo8AMoInm/Tfo3awvcq2Z6dR8EhV09WI8wWzSUibp7BuwIyAoLX8t3APC0hYupqM5wr9eXj80zMhjN8zPVWhWoEzIVmgoMsW5wZzehC8kxBUBaJ5Q7RNrnnqguFnFZTg9E91FZqyKSPM6H0KbSi8AkP3xOwyGvfnbNQftFYiXBrILhby33ANJIgdHPjw+lLpi2/S1Tqz40gQOeRu8Sm7dSRw+Hh+Srh+ubqdxUYU33rNR4Z7isJmYGfZ9u/vth8s4EvNu6eDQrTi4gGgk="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test --coverage
  - yarn build
  - yarn bundlemon
before_deploy:
  - yarn add cozy-app-publish
deploy:
  - provider: script
    repo: cozy/cozy-notes
    skip-cleanup: true
    # deploy the build on a build branch and publish to the Cozy registry
    script: DEPLOY_BRANCH=ci-build && yarn deploy && yarn cozyPublish
    on:
      branch: master
  - provider: script
    repo: cozy/cozy-notes
    skip-cleanup: true
    # publish stable or beta versions using Github Releases (git tag)
    script: DEPLOY_BRANCH=ci-build && yarn deploy && yarn cozyPublish
    on:
      tags: true
