export const DEFAULT_IMAGE_WIDTH = 250

export const DEFAULT_IMAGE_HEIGHT = DEFAULT_IMAGE_WIDTH * 0.75

export const DEFAULT_LINE_LENGTH = 768

export const DEFAULT_PCT_WIDTH =
  (DEFAULT_IMAGE_WIDTH / DEFAULT_LINE_LENGTH) * 100

export const SNAP_POINTS = [
  DEFAULT_IMAGE_WIDTH,
  DEFAULT_LINE_LENGTH * 0.5,
  DEFAULT_LINE_LENGTH * 0.75,
  DEFAULT_LINE_LENGTH
]
